; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
monitor_filters = colorize
lib_deps = 
	https://github.com/CNMAT/OSC.git
	https://git.iem.at/uc/osc_control.git
    bblanchon/ArduinoJson
	painlessmesh/painlessMesh@1.5.7

[env:c3_mini_dev]
board = lolin_c3_mini
lib_ignore = ESPAsyncTCP
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=5

[env:olimex_c3_dev]
board = esp32-c3-devkitm-1
lib_ignore = ESPAsyncTCP
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=5
	-DLED_PIN=8

[env:olimex_c3_dev0]
board = esp32-c3-devkitm-1
lib_ignore = ESPAsyncTCP
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=5
	-DLED_PIN=8
	-DOBJ_ID=0

[env:olimex_c3_dev1]
board = esp32-c3-devkitm-1
lib_ignore = ESPAsyncTCP
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=5
	-DLED_PIN=8
	-DOBJ_ID=1
	-DTEST_PECK=1

[env:olimex_c3_dev2]
board = esp32-c3-devkitm-1
lib_ignore = ESPAsyncTCP
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=5
	-DLED_PIN=8
	-DOBJ_ID=2

[env:olimex_c3_dev3]
board = esp32-c3-devkitm-1
lib_ignore = ESPAsyncTCP
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=5
	-DLED_PIN=8
	-DOBJ_ID=3

[env:olimex_c3_dev4]
board = esp32-c3-devkitm-1
lib_ignore = ESPAsyncTCP
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=5
	-DLED_PIN=8
	-DOBJ_ID=4
	-DTEST_PECK=1

[env:olimex_c3_dev5]
board = esp32-c3-devkitm-1
lib_ignore = ESPAsyncTCP
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=5
	-DLED_PIN=8
	-DOBJ_ID=5

[env:olimex_c3_dev6]
board = esp32-c3-devkitm-1
lib_ignore = ESPAsyncTCP
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=5
	-DLED_PIN=8
	-DOBJ_ID=6

[env:olimex_c3_dev7]
board = esp32-c3-devkitm-1
lib_ignore = ESPAsyncTCP
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=5
	-DLED_PIN=8
	-DOBJ_ID=7
	-DTEST_PECK=1
	-DKNOCKER_OFF_TIME_SCALE=250L

[env:olimex_c3_dev8]
board = esp32-c3-devkitm-1
lib_ignore = ESPAsyncTCP
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=5
	-DLED_PIN=8
	-DOBJ_ID=8

[env:olimex_c3_dev9]
board = esp32-c3-devkitm-1
lib_ignore = ESPAsyncTCP
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=5
	-DLED_PIN=8
	-DOBJ_ID=9

[env:olimex_c3_dev10]
board = esp32-c3-devkitm-1
lib_ignore = ESPAsyncTCP
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=5
	-DLED_PIN=8
	-DOBJ_ID=10
	-DTEST_PECK=1
	-DKNOCKER_OFF_TIME_SCALE=250L

[env:olimex_c3_dev11]
board = esp32-c3-devkitm-1
lib_ignore = ESPAsyncTCP
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=5
	-DLED_PIN=8
	-DOBJ_ID=11
	-DTEST_PECK=1
